// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/gRips.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// inv_qr_
mat inv_qr_(mat& X);
RcppExport SEXP _gRips_inv_qr_(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(inv_qr_(X));
    return rcpp_result_gen;
END_RCPP
}
// conips_ggm_
List conips_ggm_(arma::mat& S, List& elst, umat& emat, int& nobs, arma::mat K, int& maxit, double& eps, int& convcrit, int& print, List& aux);
RcppExport SEXP _gRips_conips_ggm_(SEXP SSEXP, SEXP elstSEXP, SEXP ematSEXP, SEXP nobsSEXP, SEXP KSEXP, SEXP maxitSEXP, SEXP epsSEXP, SEXP convcritSEXP, SEXP printSEXP, SEXP auxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< List& >::type elst(elstSEXP);
    Rcpp::traits::input_parameter< umat& >::type emat(ematSEXP);
    Rcpp::traits::input_parameter< int& >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type K(KSEXP);
    Rcpp::traits::input_parameter< int& >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double& >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int& >::type convcrit(convcritSEXP);
    Rcpp::traits::input_parameter< int& >::type print(printSEXP);
    Rcpp::traits::input_parameter< List& >::type aux(auxSEXP);
    rcpp_result_gen = Rcpp::wrap(conips_ggm_(S, elst, emat, nobs, K, maxit, eps, convcrit, print, aux));
    return rcpp_result_gen;
END_RCPP
}
// covips_ggm_
List covips_ggm_(mat& S, List& elst, umat& emat, int& nobs, mat& K, int& maxit, double& eps, int& convcrit, int& print, List& aux);
RcppExport SEXP _gRips_covips_ggm_(SEXP SSEXP, SEXP elstSEXP, SEXP ematSEXP, SEXP nobsSEXP, SEXP KSEXP, SEXP maxitSEXP, SEXP epsSEXP, SEXP convcritSEXP, SEXP printSEXP, SEXP auxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< List& >::type elst(elstSEXP);
    Rcpp::traits::input_parameter< umat& >::type emat(ematSEXP);
    Rcpp::traits::input_parameter< int& >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< int& >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double& >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int& >::type convcrit(convcritSEXP);
    Rcpp::traits::input_parameter< int& >::type print(printSEXP);
    Rcpp::traits::input_parameter< List& >::type aux(auxSEXP);
    rcpp_result_gen = Rcpp::wrap(covips_ggm_(S, elst, emat, nobs, K, maxit, eps, convcrit, print, aux));
    return rcpp_result_gen;
END_RCPP
}
// ncd_ggm_
List ncd_ggm_(mat& S, List& elst, umat& emat, int& nobs, mat K, int maxit, double& eps, int& convcrit, int print, List& aux);
RcppExport SEXP _gRips_ncd_ggm_(SEXP SSEXP, SEXP elstSEXP, SEXP ematSEXP, SEXP nobsSEXP, SEXP KSEXP, SEXP maxitSEXP, SEXP epsSEXP, SEXP convcritSEXP, SEXP printSEXP, SEXP auxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< List& >::type elst(elstSEXP);
    Rcpp::traits::input_parameter< umat& >::type emat(ematSEXP);
    Rcpp::traits::input_parameter< int& >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< mat >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double& >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int& >::type convcrit(convcritSEXP);
    Rcpp::traits::input_parameter< int >::type print(printSEXP);
    Rcpp::traits::input_parameter< List& >::type aux(auxSEXP);
    rcpp_result_gen = Rcpp::wrap(ncd_ggm_(S, elst, emat, nobs, K, maxit, eps, convcrit, print, aux));
    return rcpp_result_gen;
END_RCPP
}
// clone_
SEXP clone_(SEXP& x);
RcppExport SEXP _gRips_clone_(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(clone_(x));
    return rcpp_result_gen;
END_RCPP
}
// ggm_logL_
double ggm_logL_(mat& S, mat& K, int nobs);
RcppExport SEXP _gRips_ggm_logL_(SEXP SSEXP, SEXP KSEXP, SEXP nobsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< mat& >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type nobs(nobsSEXP);
    rcpp_result_gen = Rcpp::wrap(ggm_logL_(S, K, nobs));
    return rcpp_result_gen;
END_RCPP
}

// validate (ensure exported C++ functions exist before calling them)
static int _gRips_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP _gRips_RcppExport_registerCCallable() { 
    R_RegisterCCallable("gRips", "_gRips_RcppExport_validate", (DL_FUNC)_gRips_RcppExport_validate);
    return R_NilValue;
}
