# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

setdiff_ <- function(x, y) {
    .Call('_gRips_setdiff_', PACKAGE = 'gRips', x, y)
}

rep_nout <- function(x, nout) {
    .Call('_gRips_rep_nout', PACKAGE = 'gRips', x, nout)
}

vec2mat <- function(x, nrow, ncol) {
    .Call('_gRips_vec2mat', PACKAGE = 'gRips', x, nrow, ncol)
}

remove_elem <- function(X, ent_, shift = 1L) {
    .Call('_gRips_remove_elem', PACKAGE = 'gRips', X, ent_, shift)
}

extract_elem <- function(X, ent_, shift = 1L) {
    .Call('_gRips_extract_elem', PACKAGE = 'gRips', X, ent_, shift)
}

replace_elem <- function(X, ent_, value_, shift = 1L) {
    .Call('_gRips_replace_elem', PACKAGE = 'gRips', X, ent_, value_, shift)
}

remove_rows <- function(X, row_ent_, shift = 1L) {
    .Call('_gRips_remove_rows', PACKAGE = 'gRips', X, row_ent_, shift)
}

extract_rows <- function(X, row_ent_, shift = 1L) {
    .Call('_gRips_extract_rows', PACKAGE = 'gRips', X, row_ent_, shift)
}

replace_rows <- function(X, row_ent_, value, shift = 1L) {
    .Call('_gRips_replace_rows', PACKAGE = 'gRips', X, row_ent_, value, shift)
}

replace_u_vc <- function(M, u, v, value, shift = 1L) {
    .Call('_gRips_replace_u_vc', PACKAGE = 'gRips', M, u, v, value, shift)
}

replace_uc_v <- function(M, u, v, value, shift = 1L) {
    .Call('_gRips_replace_uc_v', PACKAGE = 'gRips', M, u, v, value, shift)
}

replace_uc_vc <- function(M, u, v, value, shift = 1L) {
    .Call('_gRips_replace_uc_vc', PACKAGE = 'gRips', M, u, v, value, shift)
}

replace_u_v <- function(M, u, v, value, shift = 1L) {
    .Call('_gRips_replace_u_v', PACKAGE = 'gRips', M, u, v, value, shift)
}

replace_uv_ <- function(M, u, v, value, shift = 1L) {
    .Call('_gRips_replace_uv_', PACKAGE = 'gRips', M, u, v, value, shift)
}

as_colvec <- function(M) {
    invisible(.Call('_gRips_as_colvec', PACKAGE = 'gRips', M))
}

extract_uv_ <- function(M, u, v, shift = 1L) {
    .Call('_gRips_extract_uv_', PACKAGE = 'gRips', M, u, v, shift)
}

max_abs_ <- function(S) {
    .Call('_gRips_max_abs_', PACKAGE = 'gRips', S)
}

max_abs_diag_ <- function(S) {
    .Call('_gRips_max_abs_diag_', PACKAGE = 'gRips', S)
}

max_abs_diff_rel_ <- function(S, Sigma) {
    .Call('_gRips_max_abs_diff_rel_', PACKAGE = 'gRips', S, Sigma)
}

max_abs_diff_ <- function(S, Sigma) {
    .Call('_gRips_max_abs_diff_', PACKAGE = 'gRips', S, Sigma)
}

max_abs_diag_diff_ <- function(S, Sigma) {
    .Call('_gRips_max_abs_diag_diff_', PACKAGE = 'gRips', S, Sigma)
}

max_diag_diff_ <- function(S, Sigma) {
    .Call('_gRips_max_diag_diff_', PACKAGE = 'gRips', S, Sigma)
}

califa_ <- function(S, Sigma, Sigmaold) {
    .Call('_gRips_califa_', PACKAGE = 'gRips', S, Sigma, Sigmaold)
}

diff_on_Emat_ <- function(S, Sigma, E, shift = 1L) {
    .Call('_gRips_diff_on_Emat_', PACKAGE = 'gRips', S, Sigma, E, shift)
}

diff_on_Elist_ <- function(S, Sigma, E, shift = 1L) {
    .Call('_gRips_diff_on_Elist_', PACKAGE = 'gRips', S, Sigma, E, shift)
}

max_abs_diff_on_Emat_ <- function(Sigma, S, E, shift = 1L) {
    .Call('_gRips_max_abs_diff_on_Emat_', PACKAGE = 'gRips', Sigma, S, E, shift)
}

mean_abs_diff_on_Emat_ <- function(Sigma, S, E, shift = 1L) {
    .Call('_gRips_mean_abs_diff_on_Emat_', PACKAGE = 'gRips', Sigma, S, E, shift)
}

max_abs_diff_on_Elist_ <- function(Sigma, S, E, shift = 1L) {
    .Call('_gRips_max_abs_diff_on_Elist_', PACKAGE = 'gRips', Sigma, S, E, shift)
}

mean_abs_diff_on_Elist_ <- function(Sigma, S, E, shift = 1L) {
    .Call('_gRips_mean_abs_diff_on_Elist_', PACKAGE = 'gRips', Sigma, S, E, shift)
}

max_diff_on_Emat_ <- function(Sigma, S, E) {
    .Call('_gRips_max_diff_on_Emat_', PACKAGE = 'gRips', Sigma, S, E)
}

max_abs_diff_on_EK_ <- function(S, Sigma, E, K) {
    .Call('_gRips_max_abs_diff_on_EK_', PACKAGE = 'gRips', S, Sigma, E, K)
}

make_clist_ <- function(S, edges) {
    .Call('_gRips_make_clist_', PACKAGE = 'gRips', S, edges)
}

Scc_inv_list_ <- function(S, edges0) {
    .Call('_gRips_Scc_inv_list_', PACKAGE = 'gRips', S, edges0)
}

Scc_list_ <- function(S, edges0) {
    .Call('_gRips_Scc_list_', PACKAGE = 'gRips', S, edges0)
}

.c_conips_ggm_ <- function(S, Elist, Emat, nobs, K, iter, eps, convcrit, print, aux) {
    .Call('_gRips_conips_ggm_', PACKAGE = 'gRips', S, Elist, Emat, nobs, K, iter, eps, convcrit, print, aux)
}

.c_covips_ggm_ <- function(S, Elist, Emat, nobs, K, iter, eps, convcrit, print, aux) {
    .Call('_gRips_covips_ggm_', PACKAGE = 'gRips', S, Elist, Emat, nobs, K, iter, eps, convcrit, print, aux)
}

as_emat2amat_ <- function(emat, d) {
    .Call('_gRips_as_emat2amat_', PACKAGE = 'gRips', emat, d)
}

as_emat_complement_ <- function(emat, d, shift = 1L) {
    .Call('_gRips_as_emat_complement_', PACKAGE = 'gRips', emat, d, shift)
}

inv_qr_ <- function(X) {
    .Call('_gRips_inv_qr_', PACKAGE = 'gRips', X)
}

diff_fun_ <- function(Sigma, K, emc) {
    .Call('_gRips_diff_fun_', PACKAGE = 'gRips', Sigma, K, emc)
}

outerloop1_ <- function(Sigma, K, Emat, Emat_c, amat, nobs, eps, maxit, print = 0L) {
    .Call('_gRips_outerloop1_', PACKAGE = 'gRips', Sigma, K, Emat, Emat_c, amat, nobs, eps, maxit, print)
}

.c_ncd_ggm_ <- function(S, Elist, Emat, nobs, K, iter, eps, convcrit, print, aux) {
    .Call('_gRips_ncd_ggm_', PACKAGE = 'gRips', S, Elist, Emat, nobs, K, iter, eps, convcrit, print, aux)
}

unique_rows <- function(m) {
    .Call('_gRips_unique_rows', PACKAGE = 'gRips', m)
}

unique_cols <- function(m) {
    .Call('_gRips_unique_cols', PACKAGE = 'gRips', m)
}

.c_clone <- function(x) {
    .Call('_gRips_clone_', PACKAGE = 'gRips', x)
}

list_names_ <- function(lst) {
    .Call('_gRips_list_names_', PACKAGE = 'gRips', lst)
}

find_str_ <- function(st, x) {
    .Call('_gRips_find_str_', PACKAGE = 'gRips', st, x)
}

list2Emat_ <- function(E, shift = 1L) {
    .Call('_gRips_list2Emat_', PACKAGE = 'gRips', E, shift)
}

ggm_logL_ <- function(S, K, nobs) {
    .Call('_gRips_ggm_logL_', PACKAGE = 'gRips', S, K, nobs)
}

list2row_ <- function(input_list, d = 2L) {
    .Call('_gRips_list2row_', PACKAGE = 'gRips', input_list, d)
}

list2col_ <- function(input_list, d = 2L) {
    .Call('_gRips_list2col_', PACKAGE = 'gRips', input_list, d)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_gRips_RcppExport_registerCCallable', PACKAGE = 'gRips')
})
