# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inv_qr_ <- function(X) {
    .Call('_gRips_inv_qr_', PACKAGE = 'gRips', X)
}

.c_conips_ggm_ <- function(S, elst, emat, nobs, K, maxit, eps, convcrit, print, aux) {
    .Call('_gRips_conips_ggm_', PACKAGE = 'gRips', S, elst, emat, nobs, K, maxit, eps, convcrit, print, aux)
}

.c_covips_ggm_ <- function(S, elst, emat, nobs, K, maxit, eps, convcrit, print, aux) {
    .Call('_gRips_covips_ggm_', PACKAGE = 'gRips', S, elst, emat, nobs, K, maxit, eps, convcrit, print, aux)
}

.c_ncd_ggm_ <- function(S, elst, emat, nobs, K, maxit, eps, convcrit, print, aux) {
    .Call('_gRips_ncd_ggm_', PACKAGE = 'gRips', S, elst, emat, nobs, K, maxit, eps, convcrit, print, aux)
}

.c_clone <- function(x) {
    .Call('_gRips_clone_', PACKAGE = 'gRips', x)
}

ggm_logL_ <- function(S, K, nobs) {
    .Call('_gRips_ggm_logL_', PACKAGE = 'gRips', S, K, nobs)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_gRips_RcppExport_registerCCallable', PACKAGE = 'gRips')
})
